<script setup lang="ts">
import {ref,watch} from 'vue'
import {get,post,type ApiError} from '../../shared/api'
import type {CommunityPage,Demand,DemandReply,Report} from '../community/types'
import MmButton from '../../shared/components/MmButton.vue'
import MmPagination from '../../shared/components/MmPagination.vue'
const tab=ref('demands'),status=ref('PENDING'),page=ref(0),pages=ref(0),loading=ref(false),busy=ref(false),error=ref(''),notes=ref<Record<number,string>>({}),actions=ref<Record<number,string>>({}),demands=ref<Demand[]>([]),replies=ref<DemandReply[]>([]),reports=ref<Report[]>([])
async function load(){loading.value=true;error.value='';try{const r=await get<CommunityPage<Demand|DemandReply|Report>>(`/community/admin/${tab.value}`,{status:status.value,page:page.value,size:15});pages.value=r.totalPages;if(tab.value==='demands')demands.value=r.items as Demand[];if(tab.value==='demand-replies')replies.value=r.items as DemandReply[];if(tab.value==='reports')reports.value=r.items as Report[]}catch(e){error.value=(e as ApiError).message}finally{loading.value=false}}
async function decide(id:number,approve:boolean){busy.value=true;try{await post(`/community/admin/${tab.value}/${id}/review`,{approve,reason:notes.value[id]||null});await load()}catch(e){error.value=(e as ApiError).message}finally{busy.value=false}}
async function report(id:number){busy.value=true;try{await post(`/community/admin/reports/${id}`,{action:actions.value[id]||'KEEP',note:notes.value[id]});await load()}catch(e){error.value=(e as ApiError).message}finally{busy.value=false}}
watch(tab,()=>{page.value=0;status.value='PENDING';void load()},{immediate:true})
</script>
<template><section class="mm-stack"><h1>社区审核与举报</h1><nav class="mm-actions"><MmButton :variant="tab==='demands'?'primary':'ghost'" @click="tab='demands'">求购审核</MmButton><MmButton :variant="tab==='demand-replies'?'primary':'ghost'" @click="tab='demand-replies'">回复审核</MmButton><MmButton :variant="tab==='reports'?'primary':'ghost'" @click="tab='reports'">举报处理</MmButton></nav><label>状态 <select v-model="status" @change="page=0;load()"><option value="PENDING">待处理</option><template v-if="tab!=='reports'"><option value="APPROVED">通过</option><option value="REJECTED">驳回</option><option value="HIDDEN">隐藏</option></template><option v-else value="RESOLVED">已处理</option></select></label><p v-if="error" class="mm-error" role="alert">{{error}}</p><p v-if="loading">加载中…</p><template v-if="tab==='demands'"><article v-for="d in demands" :key="d.id" class="mm-panel"><h2>{{d.title}}</h2><p style="white-space:pre-wrap">{{d.description}}</p><p class="mm-muted">{{d.authorNickname}} · {{d.region}} · 预算 {{(d.budgetMinCents/100).toFixed(2)}}—{{(d.budgetMaxCents/100).toFixed(2)}} 元</p><form class="mm-form" @submit.prevent="decide(d.id,true)"><label>审核说明<textarea v-model="notes[d.id]" maxlength="500" required /></label><div class="mm-actions"><MmButton type="submit" :disabled="busy">通过</MmButton><MmButton variant="danger" :disabled="busy||!notes[d.id]?.trim()" @click="decide(d.id,false)">驳回</MmButton></div></form></article></template><template v-if="tab==='demand-replies'"><article v-for="r in replies" :key="r.id" class="mm-panel"><p>求购 #{{r.demandId}} · {{r.authorNickname}}</p><p style="white-space:pre-wrap">{{r.content}}</p><form class="mm-form" @submit.prevent="decide(r.id,true)"><label>审核说明<textarea v-model="notes[r.id]" maxlength="500" required /></label><div class="mm-actions"><MmButton type="submit" :disabled="busy">通过</MmButton><MmButton variant="danger" :disabled="busy||!notes[r.id]?.trim()" @click="decide(r.id,false)">驳回</MmButton></div></form></article></template><template v-if="tab==='reports'"><article v-for="r in reports" :key="r.id" class="mm-panel"><h2>举报 #{{r.id}}</h2><p>对象 {{r.resourceType}} #{{r.resourceId}}</p><p>{{r.reason}}</p><RouterLink v-if="r.resourceType==='PRODUCT'" to="/admin/products">前往商品审核核查</RouterLink><p v-if="r.processNote">处理说明：{{r.processNote}}</p><form v-if="r.status==='PENDING'" class="mm-form" @submit.prevent="report(r.id)"><label>处理动作<select v-model="actions[r.id]"><option value="KEEP">保持内容</option><option value="REJECT">驳回举报</option><option v-if="r.resourceType==='PRODUCT'" value="FORWARD_TO_PRODUCT">转商品审核下架处理</option><option v-else value="HIDE">隐藏违规内容</option></select></label><label>核查说明<textarea v-model="notes[r.id]" required minlength="6" maxlength="500" /></label><MmButton type="submit" :disabled="busy">保存处理</MmButton></form></article></template><MmPagination :page="page" :total-pages="pages" @change="page=$event;load()" /></section></template>
