<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {get,type ApiError} from '../../shared/api'
import {formatTime} from '../../shared/format'
import {FULFILLMENT_STATUS_TEXT,type FulfillmentStatus,type TotalPage} from '../../shared/types'
import MmButton from '../../shared/components/MmButton.vue'
import MmPagination from '../../shared/components/MmPagination.vue'
import PriceText from '../../shared/components/PriceText.vue'
interface FinanceOrder{orderId:number;orderNo:string;buyerId:number;sellerId:number;goodsAmountCents:number;freightCents:number;goodsRefundedCents:number;freightRefundedCents:number;originalPlatformFeeCents:number;retainedPlatformFeeCents:number;platformFeeRefundedCents:number;platformFeeRefundDueCents:number;channelFeeCents:number|null;channelFeeConfirmed:boolean;expectedSellerNetCents:number|null;simulated:boolean;channel:string|null;payStatus:string;refundStatus:string;fulfillmentStatus:FulfillmentStatus;allocationStatus:string;createdAt:string;paidAt:string|null}
interface FinanceDetail{order:FinanceOrder;ledger:{id:number;entryType:string;amountCents:number;referenceType:string;referenceId:number|null;createdAt:string}[];reconciliationStatus:string;notice:string}
const from=ref(''),to=ref(''),page=ref(0),pages=ref(0),items=ref<FinanceOrder[]>([]),detail=ref<FinanceDetail|null>(null),loading=ref(false),error=ref('')
const exportUrl=computed(()=>'/api/v1/admin/finance/export.csv?'+new URLSearchParams({...from.value?{from:from.value}:{},...to.value?{to:to.value}:{}}).toString())
async function load(){loading.value=true;error.value='';try{const result=await get<TotalPage<FinanceOrder>>('/admin/finance/orders',{from:from.value,to:to.value,page:page.value,size:20});items.value=result.content;pages.value=Math.ceil(result.total/result.size)}catch(e){error.value=(e as ApiError).message}finally{loading.value=false}}
async function inspect(id:number){error.value='';detail.value=null;try{detail.value=await get<FinanceDetail>(`/admin/finance/orders/${id}`)}catch(e){error.value=(e as ApiError).message}}
const ledgerNames:Record<string,string>={PAYMENT:'支付记录',GOODS_REFUND:'商品退款',FREIGHT_REFUND:'运费退款',PLATFORM_FEE:'平台服务费',PLATFORM_FEE_REFUND:'平台费返还',CHANNEL_FEE:'渠道费'}
onMounted(load)
</script>
<template><section><h1>资金与对账</h1><p class="mm-notice">本站内部流水及预计分配；未核对渠道账单，未执行真实分账。模拟数据不代表资金到账。</p><form class="mm-panel mm-actions" @submit.prevent="page=0;load()"><label>起始日期<input v-model="from" type="date" /></label><label>截止日期<input v-model="to" type="date" /></label><MmButton type="submit" :disabled="loading">筛选</MmButton><a :href="exportUrl" download="maimai-finance.csv">导出当前日期范围 CSV</a></form><p v-if="error" class="mm-error" role="alert">{{error}}</p><p v-if="loading">加载中…</p><template v-else><article v-for="item in items" :key="item.orderId" class="mm-panel"><div class="mm-actions"><strong>{{item.orderNo}}</strong><span class="mm-chip">{{FULFILLMENT_STATUS_TEXT[item.fulfillmentStatus]}}</span><span v-if="item.simulated">本地模拟</span></div><p>成交商品 <PriceText :cents="item.goodsAmountCents" /> · 运费 <PriceText :cents="item.freightCents" /> · 已退商品款 <PriceText :cents="item.goodsRefundedCents" /></p><p>保留平台费 <PriceText :cents="item.retainedPlatformFeeCents" /> · 渠道费 <PriceText v-if="item.channelFeeConfirmed&&item.channelFeeCents!==null" :cents="item.channelFeeCents" /><span v-else>待渠道确认</span></p><p>卖家预计净额 <PriceText v-if="item.expectedSellerNetCents!==null" :cents="item.expectedSellerNetCents" /><span v-else>待渠道确认</span> · {{item.allocationStatus==='WAITING_CHANNEL'?'等待渠道分账':'暂无分配记录'}}</p><MmButton variant="ghost" @click="inspect(item.orderId)">查看内部明细</MmButton></article><p v-if="!items.length" class="mm-panel mm-muted">当前范围没有订单。</p></template><MmPagination :page="page" :total-pages="pages" @change="page=$event;load()" /><article v-if="detail" class="mm-panel"><div class="mm-actions"><h2>{{detail.order.orderNo}} 内部明细</h2><MmButton variant="ghost" @click="detail=null">收起</MmButton></div><p class="mm-notice">{{detail.notice}}</p><dl class="mm-data"><dt>初始平台费</dt><dd><PriceText :cents="detail.order.originalPlatformFeeCents" /></dd><dt>已返还平台费</dt><dd><PriceText :cents="detail.order.platformFeeRefundedCents" /></dd><dt>待返还平台费</dt><dd><PriceText :cents="detail.order.platformFeeRefundDueCents" /></dd><dt>已退运费</dt><dd><PriceText :cents="detail.order.freightRefundedCents" /></dd></dl><p v-if="!detail.ledger.length" class="mm-muted">暂无流水记录。</p><div v-for="entry in detail.ledger" :key="entry.id" class="mm-item"><div class="mm-item-body"><strong>{{ledgerNames[entry.entryType]||entry.entryType}}</strong><p class="mm-muted">{{formatTime(entry.createdAt)}}</p></div><PriceText :cents="entry.amountCents" /></div></article></section></template>
