<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { get, type ApiError } from '../../shared/api';
import { useAuthStore } from '../../shared/stores/auth';
import MmButton from '../../shared/components/MmButton.vue';
defineProps<{ title?: string }>();
interface Source { source:string; label:string; orders:number; paidOrders:number; completedOrders:number; paidCents:number|null; refundedCents:number|null; calculatedFeeCents:number|null }
interface Dashboard { generatedAt:string; timezone:string; sourceNotice:string; users:number; activeUsers:number; listedProducts:number; sources:Source[]; trend:{ date:string; orders:number; simulatedPaid:number; livePaid:number }[]; queues:Record<string,number>; issues:{ key:string; label:string; count:number }[] }
const auth=useAuthStore(), data=ref<Dashboard|null>(null), busy=ref(false), error=ref('');
const maxTrend=computed(()=>Math.max(1,...(data.value?.trend.map(d=>d.orders)??[])));
const queues=computed(()=>[
  {key:'reports',label:'举报待核查',to:'/admin/community?tab=reports',role:'OPERATOR'},
  {key:'products',label:'商品待审核',to:'/admin/products',role:'OPERATOR'},
  {key:'tickets',label:'客服待跟进',to:'/admin/support',role:'SUPPORT'},
  {key:'aftersales',label:'售后待仲裁',to:'/admin/aftersales',role:'SUPPORT'},
].filter(q=>auth.me?.roles.includes('SUPER_ADMIN')||auth.me?.roles.includes(q.role)));
const money=(value:number)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY'}).format(value/100);
async function load(){busy.value=true;error.value='';try{data.value=await get<Dashboard>('/admin/operations/dashboard')}catch(e){error.value=(e as ApiError).message}finally{busy.value=false}}
onMounted(load);
</script>
<template>
  <section class="operations">
    <header class="operations__head"><div><p class="mm-eyebrow">平台运营</p><h1>{{ title || '平台总览' }}</h1><p v-if="data" class="mm-muted">统计时间 {{ new Date(data.generatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}) }} · 北京时间</p></div><MmButton variant="ghost" :loading="busy" @click="load">刷新数据</MmButton></header>
    <p v-if="error" class="mm-error" role="alert">{{ error }}</p><p v-if="busy && !data" role="status">正在核对业务记录…</p>
    <template v-if="data">
      <div class="operations__metrics"><article><span>注册账号</span><strong>{{ data.users }}</strong><small>{{ data.activeUsers }} 个账号状态正常</small></article><article><span>在售商品</span><strong>{{ data.listedProducts }}</strong><small>账号正常且商品已上架</small></article><article><span>全部订单记录</span><strong>{{ data.sources.reduce((sum,s)=>sum+s.orders,0) }}</strong><small>包含未付款与历史体验记录</small></article></div>
      <nav class="operations__queues" aria-label="待办队列"><RouterLink v-for="queue in queues" :key="queue.key" :to="queue.to"><span>{{ queue.label }}</span><strong>{{ data.queues[queue.key] ?? 0 }}</strong><small>查看队列 →</small></RouterLink></nav>
      <section class="operations__panel"><h2>交易来源与金额</h2><p class="mm-muted">{{ data.sourceNotice }}</p><div class="operations__sources"><article v-for="source in data.sources" :key="source.source" :class="{ 'is-warning':source.source==='UNVERIFIED' && source.orders>0 }"><h3>{{ source.label }}</h3><p><strong>{{ source.orders }}</strong> 笔记录</p><small>{{ source.paidOrders }} 笔付款标记 · {{ source.completedOrders }} 笔交付完成</small><dl v-if="source.paidCents!==null"><dt>已付订单账面金额</dt><dd>{{ money(source.paidCents) }}</dd><dt>成功退款记录</dt><dd>{{ money(source.refundedCents ?? 0) }}</dd><dt>服务费账面净额</dt><dd>{{ money(source.calculatedFeeCents ?? 0) }}</dd></dl><RouterLink v-if="auth.me?.roles.some(role=>['SUPER_ADMIN','SUPPORT'].includes(role))" :to="{path:'/admin/orders',query:{source:source.source}}">核对关联订单 →</RouterLink></article></div></section>
      <section class="operations__panel"><h2>近 14 天订单趋势</h2><p class="mm-muted">按创建日统计全部来源订单。模拟与正式付款状态以当前记录为准；没有记录的日期显示 0。</p><svg class="operations__chart" viewBox="0 0 700 220" role="img" aria-label="近14天每天创建的订单数量，下方可查看明细表"><line x1="10" y1="174" x2="690" y2="174" stroke="#d7dfe5"/><g v-for="(day,index) in data.trend" :key="day.date"><rect :x="index*49+14" :y="174-day.orders/maxTrend*136" width="28" :height="day.orders/maxTrend*136" rx="4" fill="#526e82"><title>{{ day.date }}：{{ day.orders }} 笔订单</title></rect><text :x="index*49+28" :y="Math.max(22,166-day.orders/maxTrend*136)" text-anchor="middle" font-size="12" fill="#344a5b">{{ day.orders }}</text><text :x="index*49+28" y="202" text-anchor="middle" font-size="10" fill="#586b79">{{ day.date.slice(5) }}</text></g></svg><details><summary>查看每日明细</summary><div class="operations__table"><table><thead><tr><th>日期</th><th>创建订单</th><th>其中模拟付款</th><th>其中正式付款</th></tr></thead><tbody><tr v-for="day in data.trend" :key="day.date"><td>{{ day.date }}</td><td>{{ day.orders }}</td><td>{{ day.simulatedPaid }}</td><td>{{ day.livePaid }}</td></tr></tbody></table></div></details></section>
      <section class="operations__panel"><h2>关联数据核查</h2><p class="mm-muted">直接检查数据库关联，不由 AI 生成。出现异常时保留原记录，核对来源后处理。</p><ul class="operations__issues"><li v-for="issue in data.issues" :key="issue.key"><span>{{ issue.label }}</span><strong :class="{'is-warning':issue.count>0}">{{ issue.count }} 条</strong></li></ul></section>
    </template>
  </section>
</template>
<style scoped>
.operations{display:grid;gap:22px;min-width:0}.operations__head{display:flex;justify-content:space-between;align-items:center;gap:16px}.operations h1{margin:6px 0;font-size:27px}.operations h2{font-size:19px;margin:0 0 12px}.operations h3{font-size:15px;margin:0 0 12px}.operations p{line-height:1.7}.operations__metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.operations__metrics article{display:grid;gap:9px;padding:22px;border:1px solid #d8e0e7;border-radius:12px;background:white}.operations__metrics strong{font-size:32px;color:#314b60}.operations small{color:var(--mm-muted);line-height:1.7}.operations__queues{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px}.operations__queues a{display:grid;gap:10px;padding:18px;background:#edf2f6;border-radius:12px;color:#30495e;text-decoration:none}.operations__queues strong{font-size:27px}.operations__panel{min-width:0;background:white;border:1px solid #dce2e7;border-radius:14px;padding:22px}.operations__sources{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin-top:18px}.operations__sources article{padding:17px;background:#f6f8fa;border:1px solid #e1e6eb;border-radius:10px;overflow-wrap:anywhere}.operations__sources strong{font-size:25px}.operations__sources a{display:block;margin-top:15px;font-size:13px;color:#365b74}.operations dl{display:grid;grid-template-columns:1fr;gap:4px;font-size:12px}.operations dd{margin:0 0 8px;font-variant-numeric:tabular-nums}.operations dt{color:var(--mm-muted)}.operations__chart{display:block;width:100%;height:auto;min-height:160px}.operations__table{overflow-x:auto}.operations table{width:100%;border-collapse:collapse;font-size:13px}.operations th,.operations td{padding:12px;text-align:left;white-space:nowrap;border-bottom:1px solid #eee}.operations summary{cursor:pointer;padding:12px 0}.operations__issues{list-style:none;padding:0;display:grid;gap:8px}.operations__issues li{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:12px;background:#f5f7f8;border-radius:8px}.operations__issues strong{flex-shrink:0;color:#356652}.operations .is-warning{color:#a35025;background:#fff5e9}.operations__issues span{overflow-wrap:anywhere}@media(max-width:640px){.operations__head{align-items:flex-start}.operations h1{font-size:23px}.operations__metrics{grid-template-columns:1fr;gap:8px}.operations__metrics article{padding:15px;grid-template-columns:1fr auto}.operations__metrics small{grid-column:1/-1}.operations__metrics strong{font-size:26px}.operations__panel{padding:15px}.operations__sources{grid-template-columns:1fr}.operations__sources dl{grid-template-columns:1fr auto}.operations__chart{min-height:0}.operations__issues li{font-size:13px}}
</style>
