<script setup lang="ts">
import { ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { get, type ApiError } from '../../shared/api';
import { formatTime } from '../../shared/format';
import MmButton from '../../shared/components/MmButton.vue';
import MmPagination from '../../shared/components/MmPagination.vue';
import PriceText from '../../shared/components/PriceText.vue';
const route=useRoute(),router=useRouter();
interface Row { id:number; orderNo:string; buyerId:number; buyerNickname:string; sellerId:number; sellerNickname:string; source:string; fulfillmentStatus:string; payStatus:string; refundStatus:string; totalCents:number; createdAt:string }
interface Related { id:number; title:string; status:string }
interface Detail { order:Row; items:{productId:number;title:string;quantity:number;unitPriceCents:number}[]; payments:Related[]; refunds:Related[]; tickets:Related[]; deliveryMethod:string; deliveryStatus:string|null; notice:string }
const sources:Record<string,string>={SIMULATED:'模拟付款',LIVE:'正式渠道付款',HISTORICAL:'历史体验记录',UNPAID:'未付款',UNVERIFIED:'付款来源待核查'};
const states:Record<string,string>={UNPAID:'待付款',PAID:'已标记付款',PENDING_PAYMENT:'待付款',PENDING_SHIPMENT:'待发货',PENDING_DELIVERY:'待交付',WAITING_SHIPMENT:'待发货',WAITING_MEETUP:'待面交',SHIPPED:'已发货',COMPLETED:'交易完成',CANCELLED:'已取消',CLOSED:'已关闭',NONE:'无退款',PARTIAL:'部分退款',FULL:'全额退款',SUCCESS:'成功',CREATED:'已创建',REQUESTED:'已申请',FAILED:'失败',OPEN:'待处理',IN_PROGRESS:'跟进中',IN_TRANSIT:'运输中',DELIVERED:'已签收',ARRANGED:'已约定',VERIFIED:'交付已核验'};
Object.assign(states,{CREATED:'待付款',PAID_PENDING_SHIP:'已付款待发货',AWAITING_MEETUP:'待面交',REFUNDED:'已退款',RELEASED:'已结束'});
const label=(status:string)=>states[status]??status;
const source=ref(''),orderNo=ref(''),page=ref(0),total=ref(0),items=ref<Row[]>([]),detail=ref<Detail|null>(null),error=ref(''),loading=ref(false);
let generation=0;
async function load(){const current=++generation;loading.value=true;error.value='';detail.value=null;items.value=[];try{if(route.params.orderNo){const value=await get<Detail>(`/admin/orders/${encodeURIComponent(String(route.params.orderNo))}`);if(current===generation)detail.value=value}else{const value=await get<{items:Row[];total:number}>('/admin/orders',{source:source.value||undefined,orderNo:orderNo.value.trim()||undefined,page:page.value,size:15});if(current===generation){items.value=value.items;total.value=value.total}}}catch(e){if(current===generation)error.value=(e as ApiError).message}finally{if(current===generation)loading.value=false}}
function search(){void router.push({path:'/admin/orders',query:{source:source.value||undefined,orderNo:orderNo.value.trim()||undefined}});page.value=0;void load()}
watch(()=>route.fullPath,()=>{source.value=String(route.query.source??'');orderNo.value=String(route.query.orderNo??'');page.value=0;void load()},{immediate:true});
</script>
<template><section class="admin-orders mm-stack"><header><h1>{{ route.params.orderNo ? '订单关联记录' : '订单核查' }}</h1><p class="mm-muted">按订单关联买卖双方、商品、付款、退款与工单。模拟付款没有真实扣款，历史体验记录不作为资金收入。</p></header><p v-if="error" class="mm-error" role="alert">{{ error }}</p><p v-if="loading" role="status">正在读取订单…</p>
  <template v-if="!route.params.orderNo"><form class="admin-orders__search" @submit.prevent="search"><label>付款来源<select v-model="source"><option value="">全部来源</option><option v-for="(name,key) in sources" :key="key" :value="key">{{ name }}</option></select></label><label>完整订单号<input v-model="orderNo" maxlength="32" placeholder="例如 MM…" /></label><MmButton type="submit" :disabled="loading">查询订单</MmButton></form><article v-for="order in items" :key="order.id" class="mm-panel"><div class="mm-actions"><RouterLink :to="`/admin/orders/${order.orderNo}`"><strong>{{ order.orderNo }}</strong></RouterLink><span class="mm-chip">{{ sources[order.source] }}</span></div><p>买家：{{ order.buyerNickname }} · 卖家：{{ order.sellerNickname }}</p><p>{{ label(order.fulfillmentStatus) }} · {{ label(order.payStatus) }} · {{ label(order.refundStatus) }}</p><PriceText :cents="order.totalCents" /><p class="mm-muted">{{ formatTime(order.createdAt) }}</p></article><p v-if="!loading&&!items.length&&!error" class="mm-panel">没有符合条件的订单。</p><MmPagination :page="page" :total-pages="Math.ceil(total/15)" @change="page=$event;load()" /></template>
  <template v-if="detail"><RouterLink to="/admin/orders">← 返回订单核查</RouterLink><section class="mm-panel"><h2>{{ detail.order.orderNo }}</h2><p class="mm-notice">{{ sources[detail.order.source] }} · {{ detail.notice }}</p><dl class="admin-orders__facts"><dt>买家</dt><dd>{{ detail.order.buyerNickname }}（账号 #{{ detail.order.buyerId }}）</dd><dt>卖家</dt><dd><RouterLink :to="`/sellers/${detail.order.sellerId}`">{{ detail.order.sellerNickname }}</RouterLink>（账号 #{{ detail.order.sellerId }}）</dd><dt>履约与付款</dt><dd>{{ label(detail.order.fulfillmentStatus) }} / {{ label(detail.order.payStatus) }}</dd><dt>交付记录</dt><dd>{{ detail.deliveryMethod==='MEETUP'?'同城面交':'快递' }} · {{ detail.deliveryStatus?label(detail.deliveryStatus):'尚未产生交付记录' }}</dd><dt>订单金额</dt><dd><PriceText :cents="detail.order.totalCents" /></dd></dl></section><section class="mm-panel"><h2>商品快照</h2><article v-for="item in detail.items" :key="item.productId"><RouterLink :to="`/products/${item.productId}`">{{ item.title }}</RouterLink><p>{{ item.quantity }} 件 · 下单单价 <PriceText :cents="item.unitPriceCents" /></p></article></section><div class="admin-orders__records"><section class="mm-panel"><h2>付款与退款</h2><p v-if="!detail.payments.length">无付款请求记录。</p><p v-for="record in detail.payments" :key="`pay-${record.id}`">{{ record.title }} · {{ label(record.status) }}</p><p v-if="!detail.refunds.length">无退款记录。</p><p v-for="record in detail.refunds" :key="`refund-${record.id}`">{{ record.title }} · {{ label(record.status) }}</p></section><section class="mm-panel"><h2>关联工单</h2><p v-if="!detail.tickets.length">该订单暂无关联工单。</p><p v-for="ticket in detail.tickets" :key="ticket.id"><RouterLink :to="`/support/tickets/${ticket.id}`">{{ ticket.title }}</RouterLink> · {{ label(ticket.status) }}</p></section></div></template>
</section></template>
<style scoped>.admin-orders{min-width:0;overflow-wrap:anywhere}.admin-orders__search{display:flex;flex-wrap:wrap;gap:12px;align-items:end}.admin-orders__search label{display:grid;gap:8px;flex:1;min-width:180px}.admin-orders__search input,.admin-orders__search select{width:100%;box-sizing:border-box;padding:11px;border:1px solid #d4dce2;border-radius:8px;background:white;font:inherit}.admin-orders__facts{display:grid;grid-template-columns:120px 1fr;gap:14px}.admin-orders__facts dt{color:var(--mm-muted)}.admin-orders__facts dd{margin:0}.admin-orders__records{display:grid;grid-template-columns:1fr 1fr;gap:16px}.admin-orders .mm-panel p{line-height:1.8}.admin-orders h2{font-size:19px}@media(max-width:640px){.admin-orders__records{grid-template-columns:1fr}.admin-orders__facts{grid-template-columns:1fr;gap:8px}.admin-orders__facts dd{margin-bottom:10px}.admin-orders__search label{min-width:100%;font-size:16px}}</style>
