<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { get, post, type ApiError } from '../../shared/api';
import { formatTime } from '../../shared/format';
import MmButton from '../../shared/components/MmButton.vue';
const props=defineProps<{ id:number; pending:boolean }>();
interface Assessment { id:number; status:string; assessment:string|null; failureCode:string|null; model:string; createdAt:string }
interface Context { reporterNickname:string; targetNickname:string; targetOwnerId:number|null; sourceText:string; currentText:string|null; targetUrl:string|null; snapshotSaved:boolean; sameTargetReports:number; reporterDismissals:number; assessments:Assessment[] }
const context=ref<Context|null>(null),error=ref(''),busy=ref(false);
async function load(){try{context.value=await get<Context>(`/community/admin/reports/${props.id}/context`)}catch(e){error.value=(e as ApiError).message}}
async function assess(){busy.value=true;error.value='';try{context.value=await post<Context>(`/community/admin/reports/${props.id}/ai-assessment`)}catch(e){error.value=(e as ApiError).message}finally{busy.value=false}}
onMounted(load);
</script>
<template><section class="report-evidence"><p v-if="error" class="mm-error" role="alert">{{ error }}</p><template v-if="context"><dl><dt>举报人</dt><dd>{{ context.reporterNickname }}</dd><dt>被举报内容作者</dt><dd>{{ context.targetNickname || '来源账号待核查' }}</dd></dl><div class="report-evidence__source"><strong>{{ context.snapshotSaved?'举报提交时的原文快照':'当前原文（旧记录未保存提交时快照）' }}</strong><p>{{ context.sourceText }}</p><RouterLink v-if="context.targetUrl" :to="context.targetUrl">打开对应内容 →</RouterLink><details v-if="context.snapshotSaved && context.currentText!==context.sourceText"><summary>内容提交后发生变化，查看当前原文</summary><p>{{ context.currentText || '原文已不可用' }}</p></details></div><p class="mm-muted">同一内容有 {{ context.sameTargetReports }} 次举报；举报人历史被驳回 {{ context.reporterDismissals }} 次。这些计数不能单独证明恶意。</p><div class="mm-actions"><MmButton v-if="pending" type="button" variant="ghost" :loading="busy" @click="assess">{{ busy?'麦仔正在核对证据…':'请麦仔辅助核查' }}</MmButton><small>Hermes 分析仅供参考，最终由管理员依据证据处理。</small></div><article v-for="item in context.assessments" :key="item.id" class="report-evidence__ai"><p v-if="item.status==='SUCCEEDED'">{{ item.assessment }}</p><p v-else-if="item.status==='RUNNING'">分析尚未完成，请稍后刷新。超过一分钟仍未完成时可重试。</p><p v-else>本次 AI 分析未完成；请重试或直接人工核查，没有自动处理举报。</p><small>{{ formatTime(item.createdAt) }} · {{ item.model }}</small></article></template></section></template>
<style scoped>.report-evidence{margin:16px 0;display:grid;gap:12px;min-width:0}.report-evidence dl{display:grid;grid-template-columns:130px 1fr;gap:9px;margin:0}.report-evidence dt{color:var(--mm-muted)}.report-evidence dd{margin:0;overflow-wrap:anywhere}.report-evidence__source{padding:16px;border-left:3px solid #718ca1;background:#f3f6f9;border-radius:4px 10px 10px 4px}.report-evidence__source p,.report-evidence__ai p{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.85}.report-evidence__ai{padding:16px;background:#faf8ef;border:1px solid #e6dfcb;border-radius:10px}.report-evidence small{color:var(--mm-muted);line-height:1.7}.report-evidence summary{cursor:pointer;padding:10px 0}@media(max-width:480px){.report-evidence dl{grid-template-columns:1fr;gap:6px}.report-evidence dd{margin-bottom:7px}}</style>
