<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {get,post,type ApiError} from '../../shared/api'
import {useAuthStore} from '../../shared/stores/auth'
import {formatTime} from '../../shared/format'
import type {CommunityPage} from '../community/types'
import {ticketStatus,type Ticket,type SupportMessage} from './types'
import MmButton from '../../shared/components/MmButton.vue'
import MmPagination from '../../shared/components/MmPagination.vue'
const route=useRoute(),auth=useAuthStore(),ticket=ref<Ticket|null>(null),messages=ref<SupportMessage[]>([]),page=ref(0),pages=ref(0),body=ref(''),topic=ref('FEES'),busy=ref(false),error=ref(''),aiError=ref('')
const staff=computed(()=>auth.me?.roles.some(r=>['SUPPORT','SUPER_ADMIN'].includes(r))),owner=computed(()=>ticket.value?.ownerId===auth.me?.id),assigned=computed(()=>ticket.value?.assignedTo===auth.me?.id),canReply=computed(()=>ticket.value?.status!=='CLOSED'&&(owner.value||assigned.value))
const id=()=>encodeURIComponent(String(route.params.id))
async function load(){error.value='';try{ticket.value=await get<Ticket>(`/support/tickets/${id()}`);const r=await get<CommunityPage<SupportMessage>>(`/support/tickets/${id()}/messages`,{page:page.value,size:20});messages.value=[...r.items].reverse();pages.value=r.totalPages}catch(e){error.value=(e as ApiError).message}}
async function reply(){busy.value=true;error.value='';try{await post(`/support/tickets/${id()}/messages`,{body:body.value});body.value='';page.value=0;await load()}catch(e){error.value=(e as ApiError).message}finally{busy.value=false}}
async function action(kind:string){busy.value=true;try{await post(`/support/admin/tickets/${id()}/${kind}`);await load()}catch(e){error.value=(e as ApiError).message}finally{busy.value=false}}
async function aiHelp(){busy.value=true;aiError.value='';try{await post(`/support/tickets/${id()}/ai-help`,{topic:topic.value});page.value=0;await load()}catch(e){aiError.value=((e as ApiError).message||'AI暂不可用')+'。工单已经保留，请等待人工客服回复。'}finally{busy.value=false}}
watch(()=>route.params.id,()=>{ticket.value=null;messages.value=[];page.value=0;body.value='';aiError.value='';void load()},{immediate:true})
</script>
<template><section class="mm-page"><RouterLink :to="staff?'/admin/support':'/support'">← 返回客服</RouterLink><p v-if="error" class="mm-error" role="alert">{{error}}</p><template v-if="ticket"><div class="mm-panel"><h1>{{ticket.title}}</h1><span class="mm-chip">{{ticketStatus[ticket.status]}}</span><p class="mm-muted">{{ticket.ownerNickname}} · {{formatTime(ticket.createdAt)}}</p><RouterLink v-if="ticket.orderNo" :to="`/orders/${ticket.orderNo}`">关联订单 {{ticket.orderNo}}</RouterLink><div v-if="staff" class="mm-actions"><MmButton v-if="ticket.status!=='CLOSED'&&!assigned" :disabled="busy" @click="action('claim')">接管工单</MmButton><MmButton v-if="assigned&&ticket.status!=='CLOSED'" variant="ghost" :disabled="busy" @click="action('close')">问题已解决，关闭</MmButton><MmButton v-if="ticket.status==='CLOSED'" variant="ghost" :disabled="busy" @click="action('reopen')">重新开启</MmButton></div><MmButton variant="ghost" :disabled="busy" @click="load">刷新回复</MmButton></div><article v-for="message in messages" :key="message.id" class="mm-panel"><strong>{{message.authorKind==='STAFF'?'人工客服':message.authorKind==='AI'?'AI 通用规则解释':'用户留言'}}</strong><p style="white-space:pre-wrap">{{message.body}}</p><p class="mm-muted">{{formatTime(message.createdAt)}}</p></article><MmPagination :page="page" :total-pages="pages" @change="page=$event;load()" /><form v-if="canReply" class="mm-panel mm-form" @submit.prevent="reply"><label>{{staff&&!owner?'回复用户':'补充说明'}}<textarea v-model="body" required maxlength="2000" /></label><MmButton type="submit" :loading="busy">发送</MmButton></form><div v-if="owner&&ticket.status!=='CLOSED'" class="mm-panel mm-form"><h2>通用规则 AI 解释</h2><p class="mm-muted">AI 只解释所选规则，不读取本工单正文，不代替人工裁决或执行退款。未配置时直接由人工处理。</p><label>规则主题<select v-model="topic"><option value="FEES">服务费</option><option value="PAYMENT">付款</option><option value="AFTERSALES">售后</option><option value="DELIVERY">交付</option><option value="ACCOUNT">账号</option></select></label><MmButton variant="ghost" :disabled="busy" @click="aiHelp">请求规则解释</MmButton><p v-if="aiError" class="mm-notice" role="status">{{aiError}}</p></div></template></section></template>
